<?php

namespace Dusan\Bundle\SimpleBundle\Repository;

/**
 * SimpleCrudRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SimpleCrudRepository extends \Doctrine\ORM\EntityRepository
{
}
